version: "3.9"

services:
  # db:
  #   image: mysql:8.3.0
  #   container_name: mysql-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: kline
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - db_data:/var/lib/mysql
  #     - ./backend/db/mysql-config:/etc/mysql/conf.d

  kline-server:
    container_name: kline-server
    image: kline-server
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_HOST=host.docker.internal
    env_file:
      - ./backend/.env
    depends_on:
      - db

  kline-web:
    container_name: kline-web
    image: kline-web
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - kline-server
volumes:
  db_data:
